spring:
  application:
    name: projectManager
  profiles:
    active: local
  sql:
    init:
      mode: never

# swagger 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api-test
    groups-order: desc
    tags-sorter: alpha

